os: osx
osx_image: xcode10.3
rvm: 2.6.0

addons:
  homebrew:
    packages:
    - swiftlint
    update: true

cache:
  - bundler
  - pip

branches:
  only:
    - master
    - develop

env:
   global:
   - PROJECT="JSQDataSourcesKit.xcodeproj"
   - SCHEME="JSQDataSourcesKit"
   - IOS_SDK=iphonesimulator12.4
   - TVOS_SDK=appletvsimulator12.4

before_install:
  - pip3 install proselint
  - gem update --system
  - gem install bundler

jobs:
  include:
    - &test
      stage: test
      name: iOS 11.4
      env: DESTINATION="OS=11.4,name=iPhone X" SDK="$IOS_SDK"
      script:
        - set -o pipefail
        - xcodebuild -version -sdk
        - xcodebuild clean test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -enableCodeCoverage YES -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c;
      after_success:
        - bundle exec danger
        - bash <(curl -s https://codecov.io/bash)

    - <<: *test
      name: iOS 12.2
      env: DESTINATION="OS=12.2,name=iPhone X" SDK="$IOS_SDK"

    - <<: *test
      name: tvOS 12.2
      env: DESTINATION="OS=12.2,name=Apple TV" SDK="$TVOS_SDK"

    - &build-examples
      stage: build examples
      name: iOS 11.4
      env: DESTINATION="OS=11.4,name=iPhone X" SDK="$IOS_SDK"
      script:
        - set -o pipefail
        - xcodebuild -version -sdk
        - xcodebuild clean build -project Example/Example.xcodeproj -scheme Example -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c;

    - <<: *build-examples
      name: iOS 12.2
      env: DESTINATION="OS=12.2,name=iPhone X" SDK="$IOS_SDK"

    - &pod-lint
      stage: lint
      osx_image: xcode10.1
      env: SWIFT=4.2
      script: bundle exec pod lib lint --fail-fast --swift-version=$SWIFT

    - <<: *pod-lint
      osx_image: xcode10.3
      env: SWIFT=4.3

    - <<: *pod-lint
      osx_image: xcode10.3
      env: SWIFT=5.0

    - <<: *pod-lint
      osx_image: xcode11
      env: SWIFT=5.1

    - &carthage
      stage: carthage
      osx_image: xcode10.1
      name: Xcode 10.1
      script: carthage build --no-skip-current --configuration Release

    - <<: *carthage
      osx_image: xcode10.3
      name: Xcode 10.3

    - <<: *carthage
      osx_image: xcode11
      name: Xcode 11

stages:
  - test
  - build examples
  - lint
  - carthage
